version: '{build}'

image:
  - Visual Studio 2017

environment:
  AMO_JWT_ISSUER:
    secure:
      3pKDeJgH5V9+0M5PesMCmFl+8hcm8xpJl4WOotVUyZQ=
  AMO_JWT_SECRET:
    secure:
      7ohgfsJXps4S8WkKiKAJNBi5B3KwuwP+cIuBjYEf7VKEWIzMunW8lsWxhI7dWT4dAwi75zIj/9vQ5ZPlUDkBgx1ETMJGPj0Pz9zgRYF2gFw=

install:
  - npm install -g web-ext

build_script:
  - web-ext build

after_build:
  - web-ext sign --api-key=%AMO_JWT_ISSUER% --api-secret=%AMO_JWT_SECRET%

artifacts:
  - path: '**\*.xpi'

deploy:
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: QxmeJaZABwZOuoi3srTFTUYekwKE4LEkb4s+2GObE33tuw9Y2t6+wH/z3kJO/9de
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
